// Code generated by GREENPACK (github.com/glycerine/greenpack). DO NOT EDIT.

package ristretto

import (
	"github.com/glycerine/greenpack/msgp"
)

// DecodeMsg implements msgp.Decodable
// We treat empty fields as if we read a Nil from the wire.
func (z *expirationMap) DecodeMsg(dc *msgp.Reader) (err error) {
	var sawTopNil bool
	if dc.IsNil() {
		sawTopNil = true
		err = dc.ReadNil()
		if err != nil {
			return
		}
		dc.PushAlwaysNil()
	}

	var field []byte
	_ = field
	const maxFields2zgensym_b68b1c73948b1c95_3 = 2

	// -- templateDecodeMsg starts here--
	var totalEncodedFields2zgensym_b68b1c73948b1c95_3 uint32
	totalEncodedFields2zgensym_b68b1c73948b1c95_3, err = dc.ReadMapHeader()
	if err != nil {
		return
	}
	encodedFieldsLeft2zgensym_b68b1c73948b1c95_3 := totalEncodedFields2zgensym_b68b1c73948b1c95_3
	missingFieldsLeft2zgensym_b68b1c73948b1c95_3 := maxFields2zgensym_b68b1c73948b1c95_3 - totalEncodedFields2zgensym_b68b1c73948b1c95_3

	var nextMiss2zgensym_b68b1c73948b1c95_3 int32 = -1
	var found2zgensym_b68b1c73948b1c95_3 [maxFields2zgensym_b68b1c73948b1c95_3]bool
	var curField2zgensym_b68b1c73948b1c95_3 string

doneWithStruct2zgensym_b68b1c73948b1c95_3:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft2zgensym_b68b1c73948b1c95_3 > 0 || missingFieldsLeft2zgensym_b68b1c73948b1c95_3 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft2zgensym_b68b1c73948b1c95_3, missingFieldsLeft2zgensym_b68b1c73948b1c95_3, msgp.ShowFound(found2zgensym_b68b1c73948b1c95_3[:]), decodeMsgFieldOrder2zgensym_b68b1c73948b1c95_3)
		if encodedFieldsLeft2zgensym_b68b1c73948b1c95_3 > 0 {
			encodedFieldsLeft2zgensym_b68b1c73948b1c95_3--
			field, err = dc.ReadMapKeyPtr()
			if err != nil {
				return
			}
			curField2zgensym_b68b1c73948b1c95_3 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss2zgensym_b68b1c73948b1c95_3 < 0 {
				// tell the reader to only give us Nils
				// until further notice.
				dc.PushAlwaysNil()
				nextMiss2zgensym_b68b1c73948b1c95_3 = 0
			}
			for nextMiss2zgensym_b68b1c73948b1c95_3 < maxFields2zgensym_b68b1c73948b1c95_3 && (found2zgensym_b68b1c73948b1c95_3[nextMiss2zgensym_b68b1c73948b1c95_3] || decodeMsgFieldSkip2zgensym_b68b1c73948b1c95_3[nextMiss2zgensym_b68b1c73948b1c95_3]) {
				nextMiss2zgensym_b68b1c73948b1c95_3++
			}
			if nextMiss2zgensym_b68b1c73948b1c95_3 == maxFields2zgensym_b68b1c73948b1c95_3 {
				// filled all the empty fields!
				break doneWithStruct2zgensym_b68b1c73948b1c95_3
			}
			missingFieldsLeft2zgensym_b68b1c73948b1c95_3--
			curField2zgensym_b68b1c73948b1c95_3 = decodeMsgFieldOrder2zgensym_b68b1c73948b1c95_3[nextMiss2zgensym_b68b1c73948b1c95_3]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField2zgensym_b68b1c73948b1c95_3)
		switch curField2zgensym_b68b1c73948b1c95_3 {
		// -- templateDecodeMsg ends here --

		case "buckets_zid00_map":
			found2zgensym_b68b1c73948b1c95_3[0] = true
			var zgensym_b68b1c73948b1c95_4 uint32
			zgensym_b68b1c73948b1c95_4, err = dc.ReadMapHeader()
			if err != nil {
				return
			}
			if z.buckets == nil && zgensym_b68b1c73948b1c95_4 > 0 {
				z.buckets = make(map[int64]bucket, zgensym_b68b1c73948b1c95_4)
			} else if len(z.buckets) > 0 {
				for key, _ := range z.buckets {
					delete(z.buckets, key)
				}
			}
			for zgensym_b68b1c73948b1c95_4 > 0 {
				zgensym_b68b1c73948b1c95_4--
				var zgensym_b68b1c73948b1c95_0 int64
				var zgensym_b68b1c73948b1c95_1 bucket
				zgensym_b68b1c73948b1c95_0, err = dc.ReadInt64()
				if err != nil {
					return
				}
				err = zgensym_b68b1c73948b1c95_1.DecodeMsg(dc)
				if err != nil {
					return
				}
				z.buckets[zgensym_b68b1c73948b1c95_0] = zgensym_b68b1c73948b1c95_1
			}
		default:
			err = dc.Skip()
			if err != nil {
				return
			}
		}
	}
	if nextMiss2zgensym_b68b1c73948b1c95_3 != -1 {
		dc.PopAlwaysNil()
	}

	if sawTopNil {
		dc.PopAlwaysNil()
	}

	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of expirationMap
var decodeMsgFieldOrder2zgensym_b68b1c73948b1c95_3 = []string{"buckets_zid00_map", ""}

var decodeMsgFieldSkip2zgensym_b68b1c73948b1c95_3 = []bool{false, true}

// fieldsNotEmpty supports omitempty tags
func (z *expirationMap) fieldsNotEmpty(isempty []bool) uint32 {
	if len(isempty) == 0 {
		return 1
	}
	var fieldsInUse uint32 = 1
	isempty[0] = (len(z.buckets) == 0) // string, omitempty
	if isempty[0] {
		fieldsInUse--
	}

	return fieldsInUse
}

// EncodeMsg implements msgp.Encodable
func (z *expirationMap) EncodeMsg(en *msgp.Writer) (err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	// honor the omitempty tags
	var empty_zgensym_b68b1c73948b1c95_5 [2]bool
	fieldsInUse_zgensym_b68b1c73948b1c95_6 := z.fieldsNotEmpty(empty_zgensym_b68b1c73948b1c95_5[:])

	// map header
	err = en.WriteMapHeader(fieldsInUse_zgensym_b68b1c73948b1c95_6 + 1)
	if err != nil {
		return err
	}

	// runtime struct type identification for 'expirationMap'
	err = en.Append(0xa1, 0x40)
	if err != nil {
		return err
	}
	err = en.WriteStringFromBytes([]byte{0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x61, 0x70})
	if err != nil {
		return err
	}

	if !empty_zgensym_b68b1c73948b1c95_5[0] {
		// write "buckets_zid00_map"
		err = en.Append(0xb1, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x6d, 0x61, 0x70)
		if err != nil {
			return err
		}
		err = en.WriteMapHeader(uint32(len(z.buckets)))
		if err != nil {
			return
		}
		for zgensym_b68b1c73948b1c95_0, zgensym_b68b1c73948b1c95_1 := range z.buckets {
			err = en.WriteInt64(zgensym_b68b1c73948b1c95_0)
			if err != nil {
				return
			}
			// encodeGen.gBase IDENT

			// record the interface for deduplication
			var dup bool
			dup, err = en.DedupWriteIsDup(zgensym_b68b1c73948b1c95_1)
			if err != nil {
				return
			}
			if !dup {
				err = zgensym_b68b1c73948b1c95_1.EncodeMsg(en)
				if err != nil {
					return
				}
			}
		}
	}

	return
}

// MarshalMsg implements msgp.Marshaler
func (z *expirationMap) MarshalMsg(b []byte) (o []byte, err error) {
	if p, ok := interface{}(z).(msgp.PreSave); ok {
		p.PreSaveHook()
	}

	o = msgp.Require(b, z.Msgsize())

	// honor the omitempty tags
	var empty [2]bool
	fieldsInUse := z.fieldsNotEmpty(empty[:])
	o = msgp.AppendMapHeader(o, fieldsInUse)

	if !empty[0] {
		// string "buckets_zid00_map"
		o = append(o, 0xb1, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x5f, 0x7a, 0x69, 0x64, 0x30, 0x30, 0x5f, 0x6d, 0x61, 0x70)
		o = msgp.AppendMapHeader(o, uint32(len(z.buckets)))
		for zgensym_b68b1c73948b1c95_0, zgensym_b68b1c73948b1c95_1 := range z.buckets {
			o = msgp.AppendInt64(o, zgensym_b68b1c73948b1c95_0)
			o, err = zgensym_b68b1c73948b1c95_1.MarshalMsg(o) // not is.iface, gen/marshal.go:243
			if err != nil {
				return
			}
		}
	}

	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *expirationMap) UnmarshalMsg(bts []byte) (o []byte, err error) {
	return z.UnmarshalMsgWithCfg(bts, nil)
}
func (z *expirationMap) UnmarshalMsgWithCfg(bts []byte, cfg *msgp.RuntimeConfig) (o []byte, err error) {
	var nbs msgp.NilBitsStack
	nbs.Init(cfg)
	var sawTopNil bool
	if msgp.IsNil(bts) {
		sawTopNil = true
		bts = nbs.PushAlwaysNil(bts[1:])
	}

	var field []byte
	_ = field
	const maxFields7zgensym_b68b1c73948b1c95_8 = 2

	// -- templateUnmarshalMsg starts here--
	var totalEncodedFields7zgensym_b68b1c73948b1c95_8 uint32
	if !nbs.AlwaysNil {
		totalEncodedFields7zgensym_b68b1c73948b1c95_8, bts, err = nbs.ReadMapHeaderBytes(bts)
		if err != nil {
			return
		}
	}
	encodedFieldsLeft7zgensym_b68b1c73948b1c95_8 := totalEncodedFields7zgensym_b68b1c73948b1c95_8
	missingFieldsLeft7zgensym_b68b1c73948b1c95_8 := maxFields7zgensym_b68b1c73948b1c95_8 - totalEncodedFields7zgensym_b68b1c73948b1c95_8

	var nextMiss7zgensym_b68b1c73948b1c95_8 int32 = -1
	var found7zgensym_b68b1c73948b1c95_8 [maxFields7zgensym_b68b1c73948b1c95_8]bool
	var curField7zgensym_b68b1c73948b1c95_8 string

doneWithStruct7zgensym_b68b1c73948b1c95_8:
	// First fill all the encoded fields, then
	// treat the remaining, missing fields, as Nil.
	for encodedFieldsLeft7zgensym_b68b1c73948b1c95_8 > 0 || missingFieldsLeft7zgensym_b68b1c73948b1c95_8 > 0 {
		//fmt.Printf("encodedFieldsLeft: %v, missingFieldsLeft: %v, found: '%v', fields: '%#v'\n", encodedFieldsLeft7zgensym_b68b1c73948b1c95_8, missingFieldsLeft7zgensym_b68b1c73948b1c95_8, msgp.ShowFound(found7zgensym_b68b1c73948b1c95_8[:]), unmarshalMsgFieldOrder7zgensym_b68b1c73948b1c95_8)
		if encodedFieldsLeft7zgensym_b68b1c73948b1c95_8 > 0 {
			encodedFieldsLeft7zgensym_b68b1c73948b1c95_8--
			field, bts, err = nbs.ReadMapKeyZC(bts)
			if err != nil {
				return
			}
			curField7zgensym_b68b1c73948b1c95_8 = msgp.UnsafeString(field)
		} else {
			//missing fields need handling
			if nextMiss7zgensym_b68b1c73948b1c95_8 < 0 {
				// set bts to contain just mnil (0xc0)
				bts = nbs.PushAlwaysNil(bts)
				nextMiss7zgensym_b68b1c73948b1c95_8 = 0
			}
			for nextMiss7zgensym_b68b1c73948b1c95_8 < maxFields7zgensym_b68b1c73948b1c95_8 && (found7zgensym_b68b1c73948b1c95_8[nextMiss7zgensym_b68b1c73948b1c95_8] || unmarshalMsgFieldSkip7zgensym_b68b1c73948b1c95_8[nextMiss7zgensym_b68b1c73948b1c95_8]) {
				nextMiss7zgensym_b68b1c73948b1c95_8++
			}
			if nextMiss7zgensym_b68b1c73948b1c95_8 == maxFields7zgensym_b68b1c73948b1c95_8 {
				// filled all the empty fields!
				break doneWithStruct7zgensym_b68b1c73948b1c95_8
			}
			missingFieldsLeft7zgensym_b68b1c73948b1c95_8--
			curField7zgensym_b68b1c73948b1c95_8 = unmarshalMsgFieldOrder7zgensym_b68b1c73948b1c95_8[nextMiss7zgensym_b68b1c73948b1c95_8]
		}
		//fmt.Printf("switching on curField: '%v'\n", curField7zgensym_b68b1c73948b1c95_8)
		switch curField7zgensym_b68b1c73948b1c95_8 {
		// -- templateUnmarshalMsg ends here --

		case "buckets_zid00_map":
			found7zgensym_b68b1c73948b1c95_8[0] = true
			if nbs.AlwaysNil {
				if len(z.buckets) > 0 {
					for key, _ := range z.buckets {
						delete(z.buckets, key)
					}
				}

			} else {

				var zgensym_b68b1c73948b1c95_9 uint32
				zgensym_b68b1c73948b1c95_9, bts, err = nbs.ReadMapHeaderBytes(bts)
				if err != nil {
					return
				}
				if z.buckets == nil && zgensym_b68b1c73948b1c95_9 > 0 {
					z.buckets = make(map[int64]bucket, zgensym_b68b1c73948b1c95_9)
				} else if len(z.buckets) > 0 {
					for key, _ := range z.buckets {
						delete(z.buckets, key)
					}
				}
				for zgensym_b68b1c73948b1c95_9 > 0 {
					var zgensym_b68b1c73948b1c95_0 int64
					var zgensym_b68b1c73948b1c95_1 bucket
					zgensym_b68b1c73948b1c95_9--
					zgensym_b68b1c73948b1c95_0, bts, err = nbs.ReadInt64Bytes(bts)
					if err != nil {
						return
					}
					bts, err = zgensym_b68b1c73948b1c95_1.UnmarshalMsg(bts)
					if err != nil {
						return
					}
					z.buckets[zgensym_b68b1c73948b1c95_0] = zgensym_b68b1c73948b1c95_1
				}
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				return
			}
		}
	}
	if nextMiss7zgensym_b68b1c73948b1c95_8 != -1 {
		bts = nbs.PopAlwaysNil()
	}

	if sawTopNil {
		bts = nbs.PopAlwaysNil()
	}
	o = bts
	if p, ok := interface{}(z).(msgp.PostLoad); ok {
		p.PostLoadHook()
	}

	return
}

// fields of expirationMap
var unmarshalMsgFieldOrder7zgensym_b68b1c73948b1c95_8 = []string{"buckets_zid00_map", ""}

var unmarshalMsgFieldSkip7zgensym_b68b1c73948b1c95_8 = []bool{false, true}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *expirationMap) Msgsize() (s int) {
	s = 1 + 18 + msgp.MapHeaderSize
	if z.buckets != nil {
		for zgensym_b68b1c73948b1c95_0, zgensym_b68b1c73948b1c95_1 := range z.buckets {
			_ = zgensym_b68b1c73948b1c95_1
			_ = zgensym_b68b1c73948b1c95_0
			s += msgp.Int64Size + zgensym_b68b1c73948b1c95_1.Msgsize()
		}
	}
	return
}
